### ISSUE TITLE
Change curve type from quadratic to cubic

### ISSUE THREAD

**Issue by jacobxperez** [jacobxperez/atkinson-hyperlegible-pro#13]
### Discussed in https://github.com/jacobxperez/atkinson-hyperlegible-pro/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **RandomMaerks** October 19, 2023</sup>
At the moment, when a glyph has curves, they're quadratic Bézier curves.

![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/276aef52-46e8-4893-8119-d26297f79dd3)

It might be due to the fact that .ttf files of the [original Atkinson Hyperlegible fonts](https://github.com/googlefonts/atkinson-hyperlegible) were used to convert to .sfd files. TrueType fonts use quadratic curves.

Quadratic curves are usually fine, but they are a pain to edit. Unlike cubic Bézier curves where one curve has 2 end points and the control points are separated, quadratic curves have multiple "intermediate points" and 1 control point for every two consecutive points in order to compensate for that smoothness.
You can edit a cubic curve just by editing either the end points or the control points, but you'll have to edit a quadratic curve by either manually editing every single end points (which doesn't always turn out great), or by merging all the points and be left with a "set smoothness".

---

So my idea is to a) _**change the curve type to cubic**_ and b) _**manually edit each curve to be cubic**_. It sounds like a terrible idea, but it might save a lot of headaches in the future.

![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/297225cd-1db1-4247-b175-a4ada5dc1678)

You can go to Element → Font Info → Layers, then in the Font Type section, click 'All layers cubic'.
![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/34282654-d083-4d41-af92-faf2515abddc)

Once you've done that, you can merge the 'intermediate points' and fix the control points by harmonising the curves.

https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/6d2c08fc-c38a-4585-a419-5e23a008a839
</div>

**Comment by jacobxperez** [comment]
@RandomMaerks I just change the curve from quadratic to cubic let me know if this is fine or other tings need to be finish before closing this issue.

**Comment by jacobxperez** [comment]
@RandomMaerks I just noticed I forgot to harmonize the curves I'll go ahead and do that

**Comment by jacobxperez** [comment]
@RandomMaerks Curves have been harmonized using fontforge balance tool or **ctrl+shift+p**

**Comment by RandomMaerks** [comment]
@jacobxperez It looks great so far! A lot cleaner than before

There are a couple of glyphs that still have extra points, but it's pretty easy to fix.

![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/01dc0f86-d24d-4cbc-b3f4-4f90ccb21933)
![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/4573ec17-1983-418b-b45c-a13479115eb8)

**Comment by jacobxperez** [comment]
@RandomMaerks Cool!! I'll go ahead and make this fix

**Comment by jacobxperez** [comment]
@RandomMaerks This will take some time, I want to make sure I get every single one. I will keep you updated.

**Comment by jacobxperez** [comment]
@RandomMaerks I just finish removing all extra points surgically, let me know if you find any other point that needs to be removed. Allbranches have been updated

**Comment by RandomMaerks** [comment]
Might have to do it later because I won't be home in the next 3 hours

**Comment by jacobxperez** [comment]
> Might have to do it later because I won't be home in the next 3 hours

Thats fine take your time

**Comment by RandomMaerks** [comment]
The letter "d croat" `đ` still has some extra points on its bowl (Regular, Italic, and Bold):
![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/e0e88abf-f0df-4a39-bf2d-0b29669a0d00)

The lowercase letter "e" in Italic:
![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/694d7ed9-b9ca-4dba-858f-3eefd653e06a)

And in Bold Italic, the S cedilla and s cedilla lost their inflection points, which makes the middle stroke very thin:
![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/48a96e87-e56a-4ff4-b749-1dcbd8b56ca6)

Other than that, I think everything looks great!

**Comment by jacobxperez** [comment]
@RandomMaerks Ohh yeah forgot to fix the s curves I'll go ahead and fix that and the others. Thanks!!!

**Comment by jacobxperez** [comment]
@RandomMaerks I just finish fixing the remaining problems you pointed out all branches have been updated

**Comment by RandomMaerks** [comment]
@jacobxperez I guess that's everything. Thank you for helping!

Unless there's a sneaky one that we've missed, I think we can safely close this issue for now.
