### ISSUE TITLE
Community Standards

### ISSUE THREAD

**Issue by tryoxiss** [jacobxperez/atkinson-hyperlegible-pro#15]
I was actually going to make a repo like this myself a while back but couldn't figure out how to open and build the fonts source, so a contributing guide to help with that would be excellent!

**Comment by jacobxperez** [comment]
@tryoxiss Yes!! I was going to write one because I only have a small [contribution](https://github.com/jacobxperez/atkinson-hyperlegible-pro#contribute) section at the bottom of the repo

**Comment by jacobxperez** [comment]
@tryoxiss I have created a draft [contribution guide](https://github.com/jacobxperez/atkinson-hyperlegible-pro/blob/main/.github/CONTRIBUTING.md) it still needs some work I'll be working on it this week

**Comment by jacobxperez** [comment]
Rename this issue to Community Standards: 

- [ ] Contributing Guide (working on it)
- [x] Code of  Conduct 
- [x] Issue template
- [x] pull request template
