### ISSUE TITLE
The unicode Small-Latin-Letter-A-With-Ring-And-Acute isn't needed for danish support

### ISSUE THREAD

**Issue by tryoxiss** [jacobxperez/atkinson-hyperlegible-pro#16]
Hi, I don't want to be a bother but I noticed a minor issue with the project for danish language support, `Ǻ` is listed as required for that but danish does not have such a glyph. I believe you were thinking of Åå which are already supported. The only glyphs in danish not also found in english are Åå æÆ and øØ. [According to wicktionary is is not use in any language](https://en.wiktionary.org/wiki/%C7%BB) as it has no languages listed.

**Comment by jacobxperez** [comment]
@tryoxiss Thanks for this observation, once I am free I will research this further

**Comment by jacobxperez** [comment]
@tryoxiss I have done further research and you are correct it is not necessary to support danish language however it is a missing auxiliary glyph, I will rename this project to Auxiliary for  Danish/Dansk in Latin script

**Comment by jacobxperez** [comment]
@tryoxiss
![Screenshot 2023-10-21 at 00-07-02 Hyperglot a database and tools for detecting language support in fonts](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/12118650/7e38b2bc-7b8d-4ec6-b155-a80f430ef697)

**Comment by tryoxiss** [comment]
> @tryoxiss ![Screenshot 2023-10-21 at 00-07-02 Hyperglot a database and tools for detecting language support in fonts](https://user-images.githubusercontent.com/12118650/277091262-7e38b2bc-7b8d-4ec6-b155-a80f430ef697.png)

Huh thats weird, well adding a glyph never hurts! Look good imo!

**Comment by jacobxperez** [comment]
@tryoxiss We will later add that glyph because right now we are working hard on v1.4.0 which will support Vietnamese language
