### ISSUE TITLE
Website lacks accessability

### ISSUE THREAD

**Issue by tryoxiss** [jacobxperez/atkinson-hyperlegible-pro#18]
The current website styles headers with `data-` attributes which carry no sematic weight -- a fine way to do styles, but it dosen't work for headings or landmark regions which should be labled. Even within that its not consistant, as not every heading style is represented and some are skipped. Its fine to style them arbitrarly, but labeling text as a heading (even if carrying no sematic weight) feels very wrong to me.

If for some reason its really important to use the incorrect paragraph element for headings, I can at least add the heading sematics to it with `role="heading" aria-level="2"` etc.

I would be more than willing to make these fixes myself and contirbute them myself, assuming they will be merged.

![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/94419893/35eb1bbe-f02a-4633-8cfb-cccbfb93204d)
![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/94419893/908124b0-398f-4f42-ad36-809dfe773af8)

**Comment by jacobxperez** [comment]
Good call, yes I was using the data attributes to more easily play around with the hierarchy as you can change their value on the fly. But you are right they should be using the correct h1-h6 elements. If you like you can remove de data attributes and add the corresponding heading tag i will be glad to merge your request.

**Comment by jacobxperez** [comment]
@tryoxiss use `npm run dev ` to serve current development build
and `npm run build` to makes current build they will be added in the docs folder that way we can update the website in one merge

**Comment by tryoxiss** [comment]
> @tryoxiss use `npm run dev ` to serve current development build and `npm run build` to make current build they will be added automatically in the docs folder that way we can update the website in one merge

Thanks, your readme on the website branch was actually enough to get me up and running! I believe I have completed this fully in #19

**Comment by jacobxperez** [comment]
@tryoxiss Thanks for your contribution if you have any suggestion let me know before closing this issue.
