### ISSUE TITLE
O with Horn (U+01A0)

### ISSUE THREAD

**Issue by jacobxperez** [jacobxperez/atkinson-hyperlegible-pro#2]
## O with horn `Ơ` `U+01A0` and `ơ` `U+01A1`

**Comment by RandomMaerks** [comment]
Hey Jacob!
I see that you're looking for help on Vietnamese support. Is it okay if I contribute to the project?
I'm Vietnamese, and I (kinda) know how to use FontForge (just ignore my own repos, they're in a terrible state right now)

**Comment by jacobxperez** [comment]
Yes!! one of my aims with this project is to complete the Vietnamese language let me start a branch just for you

**Comment by jacobxperez** [comment]
The [Vietnamese](https://github.com/jacobxperez/atkinson-hyperlegible-pro/tree/vietnamese) branch is ready

**Comment by jacobxperez** [comment]
@RandomMaerks Let me know if you need anything else

**Comment by RandomMaerks** [comment]
Thanks for the preparation!
Progress might be slow since I'm incredibly busy this month, but I'll make sure to keep it up-to-date.

**Comment by RandomMaerks** [comment]
> @RandomMaerks Let me know if you need anything else

I might have a couple of questions when I'm working on the fonts, but I think I'm good for now

**Comment by jacobxperez** [comment]
@RandomMaerks alright, thanks for your support, I'll be glad to answer any question

**Comment by jacobxperez** [comment]
@RandomMaerks Wow!! this is absolutely beautiful!! I love it.

**Comment by RandomMaerks** [comment]
Vietnamese characters and kerning have been implemented for AH Regular and Italic.
The source files have been uploaded to the Vietnamese branch

![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/3d88ab1c-56c6-4727-8cd3-afe93cb714bb)
![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/4736325f-501b-4de2-942d-9440957be7ef)

**Comment by jacobxperez** [comment]
@RandomMaerks Wow!! It looks beautiful. I love it

**Comment by jacobxperez** [comment]
@RandomMaerks Hey how are you doing and thanks for everything the Vietnamese update is looking awesome. I am just wondering if you have any updates for the Bold and Bold Italic style.

**Comment by RandomMaerks** [comment]
Oh sorry for not updating you on the progress D:
I'm working on Bold, and everything is almost done. I just need to add kerning to the Vietnamese glyphs.

I might have more time to work on it tomorrow. I'll try my best to keep you updated 👍

**Comment by jacobxperez** [comment]
@RandomMaerks Thats awesome thanks, no worries take your time

**Comment by RandomMaerks** [comment]
A preview of Vietnamese glyphs (AHP Bold - with kerning)

![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/33a8e00c-1375-4ef1-ad27-fbc6336b8068)
![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/4d5b8eb7-9b07-436b-95e7-d21fab5a0da8)

The original 'breve' mark is really thin and doesn't match with other marks, so I thickened it slightly and made it a bit wider. 

@jacobxperez hope you like the change

**Comment by RandomMaerks** [comment]
Also the change in question: 

![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/07e61f69-69c5-4903-9ebd-14498c78060b)

**Comment by jacobxperez** [comment]
@RandomMaerks Wow!! Yes they look perfect 👍

**Comment by RandomMaerks** [comment]
AHP Bold & Bold Italic are all finished. Sources and generated fonts have been uploaded to the `vietnamese` branch.

Here are some examples that I made:
![ahp-a1](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/e5bb0448-0500-4780-aa2a-1fb8b14fa4ea)
![ahp-a2](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/bb75fade-9eac-4ec0-a71a-40ded5076863)
![ahp-a3](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/d36cc880-2975-4f73-ae50-b10d477d58d4)

@jacobxperez if you find any problems, please let me know

**Comment by RandomMaerks** [comment]
Additional documentation about the set ↓↓

![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/3bcb5dd3-2e22-4bec-86ec-81167dc02ff5)

![image](https://github.com/jacobxperez/atkinson-hyperlegible-pro/assets/109415614/7405aaa7-d922-459c-9fe3-814de532ccbf)

**Comment by jacobxperez** [comment]
@RandomMaerks Wow this is amazing you went beyond any expectations. It was one of my goals to add Vietnamese language support to Atkinson, thanks it's perfect the typography looks beautiful. I will start preparing everything for v1.4.0 and release it later this week.

**Comment by RandomMaerks** [comment]
just under two years ago, i used the original atkinson hyperlegible fonts for my assignment. i complained that it didn't have vietnamese glyphs back then

can't believe i'd be the one to do the job two years later

**Comment by jacobxperez** [comment]
@RandomMaerks That's awesome, me too I got frustrated that google wasn't doing anything to update the original typeface so I took it upon my self, to do it. Your are always welcome to contribute to this project, thanks.
