### ISSUE TITLE
No error character representation

### ISSUE THREAD

**Issue by tryoxiss** [jacobxperez/atkinson-hyperlegible-pro#43]
Not a super common issue to run into, but the font has no glyphs for either error character. These are  "tofu" / "white box" (`□`) and decode error repalcement character (`�`).

# Font Issue
While these are not common they are relatively easy to implement. Especially the white box which has common pourposes beyond being a replacement character. Replacement character (U+FFFD) is used when a specific character or sequence cannot be decoded properly. White box (U+25A1) is often used [and suggested by the unicode box block spec](https://unicode.org/charts/PDF/U25A0.pdf) to be used as a replacement character when a specific glyph is not found. It is also commonly used as a check box for printed-out forms (despite the fact ballot-box is more appropriate).

## Expected behavior
The glyphs should exist to be render-able.

## Current behavior
 Currently since no white-box exists it defaults to the decode error character if no fallback exists, which most operating systems simply display as whitespace if no fallback for that exists. Not a big issue really, but its a few easy-to-implement glyphs that prevent weird behavour in that case.

## Additional context
This is a pretty small issue all things considered, since in most cases a fallback font will exist for both cases. Still worth doing at some point though probably. Better to know of it as an issue so deciding its not important enough for now is an active choice rather than a passive one of not knowing.

**Comment by jacobxperez** [comment]
@tryoxiss The original typeface has a cross rectangular glyph, however it was not set up to be U+FFFD I will added as part of v1.4.0
