### ISSUE TITLE
Bug: Downloading the entire repo instead of the fonts from the website

### ISSUE THREAD

**Issue by NicksPatties** [jacobxperez/atkinson-hyperlegible-pro#91]
# Bug Report

Downloading the font from the website provides a zip file that contains unnecessary contents.

## Expected behavior

When I click the "Download Font" button on the page, I should be given a zip file that only contains the fonts themselves.

## Current behavior

Downloading the font from the website provides a zip file that contains the source code for the entire repository.

## How to reproduce this bug

1. Visit [the webiste](https://jacobxperez.github.io/atkinson-hyperlegible-pro/)
2. Click the "Download Font" button, or the "Download" link in the header bar, and save the zip to your drive
3. Extract the contents of the zip

You will now see the entire contents of the repo extracted in your directory, rather than just the fonts.

## Possible solution

1. Update the [current release](https://github.com/jacobxperez/atkinson-hyperlegible-pro/releases/tag/v1.5.1) with a zip file that contains the fonts and a copy of the [license agreement](https://raw.githubusercontent.com/jacobxperez/atkinson-hyperlegible-pro/main/LICENSE.txt).
2. Update the links in `index.html` and `a.html` to link to that zip file

**Comment by jacobxperez** [comment]
@NicksPatties thanks for submitting an issue I will built a new branch containing only the release files and link them directly to the download button on the website

**Comment by jacobxperez** [comment]
@NicksPatties issue has been fix [Atkinson Hyperlegible Pro](https://jacobxperez.github.io/atkinson-hyperlegible-pro/)
